### PR TITLE
UHM-5517: Unable to Save Some Forms when Visit Location does not matc…

### PR DESCRIPTION
**Pull request by mogoodrich**
…h Session Location

### CODE REVIEW

**Comment by mogoodrich** [comment]
@BranfordTGbieor  we recently discovered a bug that could make it impossible for users to save a form if their session location wasn't equal to the visit location (or one of it's "children") of the current visit.

This shouldn't happen in the Liberia use case, since we only have 1 Visit Location per server, but I wanted to copy over some of the fixes we made to our main forms, and add some comments to others reminding us that we will have to fix it if we ever support multiple visit locations in Liberia.

Take a look and let me know if you have any objections.  I am off tomorrow, but will look to merge this in on Monday and do some testing... thanks!

**Comment by BranfordTGbieor** [comment]
Thanks, @mogoodrich. I will take a keen look at this before the end of tomorrow and give the necessary feedback. Enjoy your day off buddy😊

**Review by BranfordTGbieor — APPROVED** [review]
@mogoodrich, I've gone through and the changes look good to me. Thanks!

**Comment by mogoodrich** [comment]
Great, thanks @brandones !

**Comment by mogoodrich** [comment]
great, thanks @BranfordTGbieor !

**Pull request merged**
