### PR TITLE
LIB-63 Changed action name of Mental Health form

### PR DESCRIPTION
**Pull request by lnball**
This doesn't work.  Don't know why.

### CODE REVIEW

**Review by mogoodrich — APPROVED** [review]
LGTM, thanks @lnball !

**Review by mogoodrich — COMMENTED** [review]
Actually, wait, I need to remind myself of how this actually works, will follow up!

**Comment by lnball** [comment]
@mogoodrich Unfortunately this doesn't work.  Doesn't break anything, but doesn't change the action label.

**Comment by mogoodrich** [comment]
Will take a look @lnball

**Pull request merged**
