### PR TITLE
Enable SPA Preview for 'harper-dev'

### PR DESCRIPTION
**Pull request by brandones**
I assume this is a CI server

### CODE REVIEW

**Comment by mogoodrich** [comment]
I'm not sure what it is... :)  @BranfordTGbieor  is these dev/demo server you use in Harper?

**Comment by BranfordTGbieor** [comment]
SPA Preview?? No, I am also not sure what that is @mogoodrich.

**Comment by mogoodrich** [comment]
SPA preview is a new preview of OpenMRS 3.0 (which is a single-page app, which is where SPA comes from).  

Brandon has been enabling it on staging servers so we all can see what it looks like (but obviously not production servers).  We were unclear what server "harper-dev" referred to.

**Comment by BranfordTGbieor** [comment]
Thanks, @mogoodrich, I know what SPA is but just didn't know what that "SPA Preview" config was. Thanks for the clarification. 
The "harper-dev" config was used as a toggle for forms that are still been developed -specifically the ANC forms. We didn't want the partly developed ANC forms to appear on kouka while still been developed.

**Comment by brandones** [comment]
Great, it sounds like SPA Preview would be a good fit for that server, then.

**Pull request merged**
