### PR TITLE
UHM-4683 Move Location Tag Setup out of PIH Core and into Config

### PR DESCRIPTION
**Pull request by brandones**
https://pihemr.atlassian.net/browse/UHM-4683

See https://github.com/PIH/openmrs-module-pihcore/blob/9375d67f308288387fda5e115a16091de75ea4f9/api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java#L172

### CODE REVIEW

**Comment by brandones** [comment]
Hey @lnball — this is the new format for specifying Location Tags. Maybe you could double-check these against the existing [configuration in pihcore](https://github.com/PIH/openmrs-module-pihcore/blob/6d58bd64741bbcf07b0628f23c9b1cd7163a590f/api/src/main/java/org/openmrs/module/pihcore/setup/LocationTagSetup.java#L172?)

**Comment by lnball** [comment]
@BranfordTGbieor Knows Liberia locations.  I defer to him to review the new configuration against the existing ones in pihcore

**Comment by BranfordTGbieor** [comment]
Thanks @lnball , will definitely do so!

**Comment by BranfordTGbieor** [comment]
Hey @lnball and @brandones , I think the new format for specifying Location Tags is clear and understandable.

**Comment by lnball** [comment]
This config will make it the same for Pleebo and JJ Dossen @mogoodrich @brandones ?

@BranfordTGbieor Does the location information conform with what you want for Liberia?  
https://github.com/PIH/openmrs-config-pihliberia/pull/25/files

**Comment by BranfordTGbieor** [comment]
Not really @lnball . There's one location(which I added recently) missing. I'm issuing a PR on that now.

**Comment by brandones** [comment]
@mogoodrich Verified tag re-creation.

@BranfordTGbieor Can we merge this, and then update it with the new location in a separate PR?

**Comment by brandones** [comment]
@BranfordTGbieor Can we merge this and handle updates in a separate PR?

**Comment by BranfordTGbieor** [comment]
Hey @brandones , I think that makes a lot of sense. Thanks buddy.

**Pull request merged**
